### ISSUE TITLE
[Req] Documents details page

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#171]
Information requested to be visible on document details page:
- [x] description/abstract
- [x] chapters
- [x] volumes (not implemented yet) - another issue
- [x] editions (not implemented yet) - another issue
- [ ] attached files (not implemented yet) - another issue
- [x] links
- [x] display if e-book available

**Comment by kpsherva** [comment]
closing as stale, separate issue fo the last functionality
