### ISSUE TITLE
Loan request - block loan request button if already requested

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#482]
When requesting a loan for a document, the user should see different states depending on the circumstances. Currently there are 2 states:

1. User is not logged in, (s)he has to sign in to be able to request a loan.
2. User is logged in and has no requests on the document, (s)he should be able to request a loan.

The goal is to add 2 new states:

3. User is logged in and already has a request for that document, (s)he should have a link to redirect him to the `Your loans` page and not have the request button available.
4. User is logged in and has a current loan active on the document, (s)he should be able to apply for an extension.

Potential enhancements:

- Refactor the field `circulation` in the `Document` resolver to possibly make less ES calls to improve performance.

### Tasks

- [x] Add a serializer to the documents with the new fields: `user_has_request: true | false`, `user_has_loan: true | false` and `user_last_loan:<date> | null`.
- [x] Add new test for the new documents serializer.
- [x] Refactor the field `circulation` in the `Document` resolver

Frontend task: https://github.com/inveniosoftware/react-invenio-app-ils/issues/116
