### ISSUE TITLE
UI redesign with bettter UX

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#519]
DETAILED tasks: https://github.com/inveniosoftware/invenio-app-ils/projects/2?add_cards_query=is%3Aopen

Find reference pages
With having on mind the requirements in the following issues
Both on the backoffice and front

*Global*: 
- [x] Work on naming policy for the styling classes (maybe semantic has something proposed)
- [x] find a way to make backoffice and front site theming not dependant on each other (might be actually connected with the class naming)
- [x] is there a way of using `ResultsTable` on the front site and backoffice ❓ 

*Front*:
- [x] Document details page
- [x] landing page - specify sections
- [x] search page - specify facets, ordering, sorting
- [x] patron profile page - specify columns of the tables of the loans

*BackOffice*:
- [x] specify what should be displayed on each page
- [x] specify which columns should be displayed on each page with search results or tables
- [x] specify the order/ visibility of the components in each of the details pages - with features prioritising
- [x] specify facets, sorting options, etc for search pages
- [x] implement improvements
- [x] implement styling

**THINGS TO REMEMBER**
1. we change loaders on search pages to contain all the search components ( facets, results ) except from search bar

**TASKS**

*all*
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/340 Collection of UI/UX examples

*frontsite*
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/220 Frontsite: searchpage
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/540 details page
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/541 landing page
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/528 Responsive card grid 

*backoffice*

- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/200 Document search facets and sort options
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/219 Backoffice tables UX
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/238 Backoffice UX
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/364 FACETS
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/421 Document details
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/422 Item details
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/423 Loan details
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/426 Patron details
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/427 Eitems search page
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/428 Item search page
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/474 Series show No of documents
- [x] ~https://github.com/inveniosoftware/invenio-app-ils/issues/475 Authors facet~
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/533 Backoffice sidebar
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/550 Cards instead of tables
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/237 Documents: sort by publication year
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/680 Show edition and date for each document
- [x] https://github.com/inveniosoftware/invenio-app-ils/issues/681 Items search: search suggestion by `Shelf`
- [ ] https://github.com/inveniosoftware/invenio-app-ils/issues/577 SPA Auth pages
