### ISSUE TITLE
Overdue loan reminder: show last sent

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#523]
Show in the UI last sent email manual or automatic so that the librarian can know when it was last sent.

## Solution

Sent emails (not the body) will be stored in the database. The UI will fetch data from a new API endpoint.

**DB table cols:**

| col name | type | description |
|-|-|-|
| id | number | autoincrement primary key |
| message_id | UUID | the UUID of the mail message |
| triggered_on | datetime | when the email was sent |
| triggered | string | if the email was triggered by a librarian (manually) or a celery task (automatically) |
| recipient_user_id | number | a real user id, the type of the col should be the same as the one in the accounts tables |
| email_action | string | keep track of the action that triggered the email, e.g. checkout, checkin |
| send_log | long string | information from log_successful_mail/log_error_mail (they are the celery task callback functions) |
| loan_pid| string | the pid of the loan if the email is related to a loan (optional) |

**Tasks**

- [x] create db table with the fields above
- [x] create admin panel display
- [x] anonymize rows in the db table when users are anonymized
- [x] create api endpoint with list/item views:
  - [x] list: `/api/emails`
  - [x] list by user: `/api/emails?recipient_user_id=<>` and by loan_pid and email_action
  - [x] item: `/api/emails/<id>`
- [x] test endpoint protection (admins/librarians should have access)
- [x] display in frontend backoffice how many reminders were sent for each overdue loan
