### ISSUE TITLE
Book cover provider

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#560]
## Problem

Covers for our literature are provided by a configurable third party service. ILS should provide an interface for customisation. 

## User Stories 

There are two user profiles for our stories, the developer `dev`, `librarian` and `user`

- [x] As `dev`, I need to configure my book cover provider or repository of covers.
- [x] As `dev`, I should be able to get different size of covers.
- [x] As `dev` & `lib`, I need to be able to override the `No Cover`.
- [x] As a `user` I should be able to see the medium size image or `No Cover` in front-site suggestions `Popular topics`, `Most Loaned` etc ..
- [x] As `user` I should be able to see the large size image or `No Cover` for document details.
- [x] As `user` I should be able to see the medium size image for or `No Cover` for document search grid view.
- [x] As `user` I should be able to see the small size image for or `No Cover` for document search list view.
- [x] As `user` I should experience the same cases in mobile too.
- ~[ ] As a `librarian` if there are multiple covers available, I want to choose which one to use.~

## Other
- [x] `cover_metadata` for literature
- Order of the ISBN's matters. When an item gets associated/dissociated with document a cron jobs checks/updates the order of ISBNs. There are ISBNs in `document.identifiers` and in `document.items`. We have to check them in an order from newer to older and the first one which returns a valid cover should be placed first in the list. Added to CERNDocumentServer/cds-books#92
- [x] Journals have also covers, replace the `isbn` with `issn` url parameter.

related CernDocumentServer/cds-books#92

**Comment by ntarocco** [comment]
Please remember to add a section in the InvenioILS doc explaining about this `cover_metadata` field, how you can use it to build your own URLs.
