### ISSUE TITLE
Enable SPA authentication

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#577]
When Invenio will be able to correctly handle authentication, apply the needed changes to ILS:

- [x] BUG/BLOCKER - Login stuck: https://github.com/inveniosoftware/invenio-app-ils/issues/709
- [x] Implement authentication with local account and oauth
  - [x] login
    - [x] Implementation
    - [x] Styling page (INDEPENDENT)
  - [x] logout
    - [x] Implementation
  - [ ] signup (ALMOST INDEPENDENT) Depends on invenio-accounts#master but CAN be implemented) (LATER) - issue created
  - [ ] psw forgotten (ALMOST INDEPENDENT) Depends on invenio-accounts#master but CAN be implemented) (LATER) - issue created
  - [x] email confirmation
    - [x] Implementation
    - [x] Styling page. The page that it is shown when the user is clicking the confirmation link and redirects to the UI. (INDEPENDENT)
- [x] Inject user profile/roles info in the cookie/JWT token. Replaced by `/me` endpoint.
- [ ] make sure frontsite/backoffice views are correctly protected: https://github.com/inveniosoftware/invenio-app-ils/issues/90. *I think this can be double checked and closed.*
  - [ ] Frontsite: document requests form should require login (INDEPENDENT)
  - [ ] Frontsite: menu/patron views should require login (INDEPENDENT)
- [x] if possible, get rid of `invenio-accounts-rest`
    - [x] Package was removed. Using `patrons` index for fetching patron information.
    - [x] Check if https://github.com/inveniosoftware/invenio-app-ils/issues/408 is still needed (CRUD operations) and close it if not.
- [ ] ensure all UI modules not are not needed are removed, e.g. `invenio-records-ui`, `invenio-search-ui` (INDEPENDENT) 
- [ ] style the remaining Jinja views, if needed: `/account`. (LATER) - decide if SPA or server side, review which endpoints from invenio we keep, and which ones on SPA

- [ ] Review all the code that uses `current_user` information outside a react component and therefore needs to take information from `SessionManager`. If we get rid of these places then the implementation could be simplified by removing the `SessionManager` class. (INDEPENDENT) (LATER)
- [ ] inject the first and last name of the user in the `/me` response

**Comment by kpsherva** [comment]
The issue has been split on smaller chunks
