### ISSUE TITLE
Series: serial (journals)

### ISSUE THREAD

**Issue by agentilb** [inveniosoftware/invenio-app-ils#579]
List of tasks:
- [x] Enhance series data model (#697)
- [x] Investigate how to search for journal filtering out issues (docs) on frontsite search page: new search endpoint vs multi-index on /api/documents + flag (#700)
- [x] Skip resolving for parents (#700)
- [x] Add `PERIODICAL_ISSUE` to `document_type` and revert the field from vocabulary to enum (#700)
- [x] Add series detail page to frontsite displaying all issues (#726)
- [x] Display search results for journals without displaying issues - change doc type facet to un-select by default `PERIODICAL_ISSUE` (#700)
- [x] Change frontsite routing (#726)
- [ ] Add volume/issue pairs to relation metadata (still to be discussed with the library) https://github.com/inveniosoftware/invenio-app-ils/issues/729
- [x] Apply final changes to data model (structured access object)
- [ ] Serial to serial relations (https://github.com/inveniosoftware/invenio-app-ils/issues/717)

---

Periodicals are series of volumes/issues. Each volume/issue has a set of articles. Some volume/issue can be read at the library or loaned.
We are not modeling the articles.

As example, we can use the journal `Nuclear Physics B` (https://cds.cern.ch/record/229708)

Periodical/journal
---

A periodical/journal will be modeled as a `Series` with `mode_of_issuance: SERIAL`. It will "contain" a list of `Documents`, the volumes/issues.
A `Series` can be linked to another series (e.g. `Nuclear Physics B` is linked to the previous `Nuclear Physics A`).
The `Series` object should be extended with the following fields:

| Field name | type |
| - | - |
| title | string |
| abbreviated_title | string |
| alternative_titles | list of `alternative_titles` as in Document |
| identifiers | list of `identifiers` as in Document (scheme, value, material) |
| urls | list of `urls` as in Document (value, description) |
| access_urls | list of `urls` as in Document (value, description) + `open_access` + `restricted vocabulary` (e-holdings) |
| note | as in Document |
| internal_notes | as in Document |
| publisher | list of strings |

Volume/Issue
---

A volume/issue will be modeled as a `Document` with `document_type:JOURNAL_VOLISSUE` (or similar).
The document will have, as title, the name of the vol/issue, e.g. "Volume 950 Issue 3". It might be extended with a `journal_volume` object containing one or two fields to model the `volume` and `issue`, for search purposes.
The document is "linked" to its `Series`, the periodical.

Physical copy of volume/issue
---

A physical copy, for circulation or reference only, will be modeled as an `Item`, as for books.

---

Original description below (Check the comments also):

Here is below a table listing all the fields we need to store for the journals in CDS. 
I've simplified it from what we have currently in Marc. 

The main information is the description of the "e-holdings" which is a link to the journal on the publisher website with the description of the access (from which volume/year to which volume/year, what is the access type: open access, perpetual purchased access, national license, rolling window...).

We have also a field to describe the  paper holdings: description of the collection from start volume and year to the end volume and year, and location. This field is redondant with the information of the items themselves, but given that for journals we can have hundreds of items, it is easier for the user to have a description of the collection and not a simple list of items (unless this can be extracted from the list of items?)

  | properties | description |   | Mandatory | MARC
-- | -- | -- | -- | -- | --
title |   | title of the journal |   | x | 245__a/b
alternative_titles |   | alternative title |   |   | 246__
relation |   | link to a previous title or the replacement title, link to a supplement |   |   | 780,(continues 787(language), 785(continued by), 775 (potentially edition)
url |   | external link which is not the link to the resource itself |   |   | 85642u/y
Intenal_notes |   | note for the librarian |   |   | 937__a
notes |   | note for the public |   |   | 935__a
document_type |   | periodical |   | x | 980__a
publisher |   | publisher name | list | x | 933__b
identifier | value | For the time being, we only have ISSN as identifier. | string (with possible validation) |   | 022__a
  | Scheme |   |   |   | 022__b
abbreviated_title |   | all journals have an abbreviated title : can also be in alternative title | string | x | 210__a
e-holding | Start volume and year |   |   | Either e- or p-holding is mandatory | 856413
  | End Volume and year |   |   |   | 856413
  | url |   |   |   | 85641u
  | Access type |   |   |   | 85641x
  | Public note |   |   |   | 85641z
p-holding | Start volume and year |   |   |   | 866__a
  | End Volume and year |   |   |   | 866__a
  | location |   |   |   | 866__b
  | Public note |   |   |   | Does not exist

COMMENT: 
this task is connected with `publication_year` field of the document schema. if the journal will be modelled as a series or document this field needs to be re-descussed and changed

**Comment by agentilb** [comment]
Update: maybe e-holding should be a separate element, similarly to e-item. Since we can have several occurrences of this field.

**Comment by ntarocco** [comment]
Periodicals are series of volumes/issues. Each volume/issue has a set of articles. Some volume/issue can be read at the library or loaned.
We are not modeling the articles.

As example, we can use the journal `Nuclear Physics B` (https://cds.cern.ch/record/229708)

Periodical/journal
---

A periodical/journal will be modeled as a `Series` with `mode_of_issuance: SERIAL`. It will "contain" a list of `Documents`, the volumes/issues.
A `Series` can be linked to another series (e.g. `Nuclear Physics B` is linked to the previous `Nuclear Physics A`).
The `Series` object should be extended with the following fields:

| Field name | type |
| - | - |
| title | string |
| abbreviated_title | string |
| alternative_titles | list of `alternative_titles` as in Document |
| identifiers | list of `identifiers` as in Document (scheme, value, material) |
| urls | list of `urls` as in Document (value, description) |
| access_urls | list of `urls` as in Document (value, description) + `open_access` (e-holdings) |
| note | as in Document |
| internal_notes | as in Document |
| publisher | list of strings |

Volume/Issue
---

A volume/issue will be modeled as a `Document` with `document_type:JOURNAL_VOLISSUE` (or similar).
The document will have, as title, the name of the vol/issue, e.g. "Volume 950 Issue 3". It might be extended with a `journal_volume` object containing one or two fields to model the `volume` and `issue`, for search purposes.
The document is "linked" to its `Series`, the periodical.

Physical copy of volume/issue
---

A physical copy, for circulation or reference only, will be modeled as an `Item`, as for books.

**Comment by agentilb** [comment]
Here are values we can have when we describe the access type of an online subscription: 
- Open Access
- Restricted access: National License
- Restricted access: Perpetual access subscription
- Restricted access: Perpetual access backfiles
- Restricted access: Package deal
- Restricted access: Undefined

-> The user should only see the distinction Open Access / Restricted access. 
The additional details is for the back office. 

I leave it to you to see if it makes sense to have 2 fields instead, e.g.: 
- Open Access: boolean (Mandatory)
- Restricted access type (Not Mandatory)

I confirm the public_note is important at this level as well, because for the "Open Access", it is sometimes useful to add some additional information.

**Comment by kpsherva** [comment]
Two sub tasks left, transferred to new issues
