### ISSUE TITLE
Document request: add `medium` fields

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#633]
When the patron request a new book that is not in the library catalogue, (s)he will have to fill the Document Request form. The form needs to be enhanced with the new field `medium` and values `Paper or Print` and `E-book` or `Electronic`.

## Tasks

- [x] change the data model (jsonschema) and add the new fields
- [x] change the ES mapping and add the new fields
- [x] change the JSON loader to accept the new fields

Frontend: https://github.com/inveniosoftware/react-invenio-app-ils/issues/99
