### ISSUE TITLE
InterLibrary Loans

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#637]
Scenario 
---
A patron does not find the literature that he is looking for in the catalog and (s)he creates a request for a new literature. The librarian decides to fulfil the request with an InterLibrary Loan.

User stories
---
- As a patron, I create a new literature request specifying that I am interested in a new loan
  - [x] already implemented by Document Request EPIC
- As a patron, I can see the ILL loan in my profile page
  - [x] show current loans borrowing requests of the patron in a different section e.g. Interlibrary loans. Show past loans borrowing requests as normal loan (the patron does not care much if it was an ILL) https://github.com/inveniosoftware/invenio-app-ils/issues/810
- As a patron, I receive an e-mail when the item is ready to be picked up
  - [x] check if already fulfilled by circulation workflow
- As a patron, I receive an e-mail when the loan has started with the duration of the loan
  - [x] check if already fulfilled by circulation workflow
- As a patron, I receive an e-mail when the loan is about to expire so that I can take actions
  - [x] Ensure that e-mail reminder is sent before ILL loan expires: https://github.com/inveniosoftware/invenio-app-ils/issues/707
- As a patron, I can request for extension when the loan is about to expire
  - [x] Extension data model https://github.com/inveniosoftware/invenio-app-ils/issues/708
  - [x] Patron can request ILL extension in his profile page https://github.com/inveniosoftware/invenio-app-ils/issues/869
- As a patron, when the extension request is accepted, I receive an e-mail with the new end date of the loan
  - addressed in https://github.com/inveniosoftware/invenio-app-ils/issues/870
- As a patron, when the extension request is declined, I receive an e-mail that informs me that I need to bring back the item
  - addressed in https://github.com/inveniosoftware/invenio-app-ils/issues/870
- As a patron, when I have requested an extension or it has been rejected, I cannot request it any more.
  - addressed in https://github.com/inveniosoftware/invenio-app-ils/issues/869

- As a librarian, I find the new pending literature request in the backoffice and I fulfil the request with a new ILL.
  - [x] Create ILL from Document Request https://github.com/inveniosoftware/invenio-app-ils/issues/706
  - [x] Add `restricted` field to document https://github.com/inveniosoftware/invenio-app-ils/issues/687
- As a librarian, I can input the details of the physical ILL borrowing request when sent to the external library
  - Librarian inputs all the details in the borrowing request record
  - Librarian changes the status to `ORDERED`
  - [x] ILL BorrowingRequest data model and U:I https://github.com/inveniosoftware/invenio-app-ils/issues/705
- As a librarian, when I receive the requested item from the external library, I can change the status to `RECEIVED`.
  - [x] done with editor form https://github.com/inveniosoftware/invenio-app-ils/issues/705
- As a librarian, when the item is checked out by the patron, a new loan is created with the duration matching the borrowing request duration and the borrowing request status is `ON LOAN`
  - [x] Enable circulation of different types of items: https://github.com/inveniosoftware/invenio-app-ils/issues/702
  - [x] Create a new loan from the Borrowing Request backoffice details page: https://github.com/inveniosoftware/invenio-app-ils/issues/819
- As a librarian, when I receive an extension request for an ILL by e-mail or see in the backoffice, I can accept or reject it. 
  - [x] Librarian can accept or decline an extension request https://github.com/inveniosoftware/invenio-app-ils/issues/870
- As a librarian, when I accept an extension request, I input the new end date for the loan and the patron is notified.
  - [x] addressed in https://github.com/inveniosoftware/invenio-app-ils/issues/870
- As a librarian, when I reject an extension request, the patron is notified.
    - [x] addressed in https://github.com/inveniosoftware/invenio-app-ils/issues/870

ILL platform in the market, for inspiration: https://support.atlas-sys.com/hc/en-us/categories/360000716874-ILLiad
**Note:** use the label `Interlibrary loan` when displaying `ILL` or `BorrowingRequest` to the patron/library.

Extra tasks
---
- [x] Loans should have base32 PIDs: https://github.com/inveniosoftware/invenio-app-ils/issues/703
- [x] Remove config ILS_DEFAULT_LOCATION_PID and inject in the `/me` payload: https://github.com/inveniosoftware/invenio-app-ils/issues/704
- [ ] Nice to have: disable some of the email sending, e.g. reminders
