### ISSUE TITLE
Series: add serial (journals)

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#694]
- [ ] Enhance series data model (#579)
- [ ] Allow serial to serial relations
- [ ] Add `PERIODICAL_ISSUE` to `document_type` vocabulary
- [ ] Add series detail page to frontsite
- [ ] Display search results for journals
- [ ] Change frontsite routing
- [ ] Add volume/issue pairs to relation metadata (still to be discussed with the library)

**Comment by kpsherva** [comment]
closing as a duplicate of https://github.com/inveniosoftware/invenio-app-ils/issues/579
