### ISSUE TITLE
patron cancel literature request

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#743]
- [x] patron can cancel its own literature request
- [x] rename the `PendingRequestResource` to be more explicit
- [x] fix the loader of `PendingRequestResource` to explicitly accept only document_pid or physical...provider and check for `state == PENDING`
- [x] rename the front-end from onChangeDoc to onRemovedDoc
- [x] cast patron id to string in `fetchProfile` method
- [x] #742 add the `circulation` field in the loan resolver in `loan.py:document_resolver(loan_pid)`
- [x] fix OrderSubmitForm serializer from #738 
- [x] restructure document-request endpoints per property and not action
- [x] confirmation modal for canceling literature request
- [x] tests for permissions
- [x] fix `list_permission_factory_imp`: patrons can search only their own doc reqs
- [ ] ~~patron can cancel its own loan when it is in `PENDING` state~~ #598
