### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#772]
ILS should come by default with a set of static pages similar to what users can find in a website. The default content can be something fake because it must be customizable.

Pages to create by default in ILS:
- About Us
- Contacts 

Each page should have simply a title and a content. Static pages links should be displayed in the footer.

What should be customizable (already supplied by invenio-pages:
- the title
- the content
- the name of the link (can differ from the title)
- the URL, if possible

The overlay that overrides ILS should be able to map the routing from pages in react to pages in /api
```
const staticPages = {
  { name: 'about', route: '/about', apiURL: '1' }
]}
```
The overriding is possible by changing this variable in the overlay

Tasks
---

1. Add to `react-router` the possibility of defining routes by config (this `link.urlPath`)
2. Implement the generic static page cmp

Decisions
----------
- [ ] decided not to overwrite the individual pages as react components - every time changing the content of such a page would require a deployment of react app. Instead the pages will be fetched from invenio-pages, where static page can be easily edited, with a simple formatting editor included
- [ ] overridable component will be the footer of the frontsite -  the footer is for now injectable by a `renderElement` function, until the strategy for components is established
- [ ] custom pages (from any overlay) will be added as a param to the routing

**Comment by topless** [comment]
These are the slides from indico on how they override react components might be worth having a look.

https://codimd.web.cern.ch/p/By7Ar3fUN#/
