### ISSUE TITLE
GDPR: right to be forgotten

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#925]
In case of patron request, the system should allow to anoymise any activity.

### Tasks

- [x] create a callable function that can return all patron activity
- [x] create a callable function that will replace any patron info with anonymous info: this involves both DB and ES indexing
- [x] create 2 CLI commands that can call these 2 functions: the listing activity should display a nice report, the anonymization should ask for confirmation (irreversible operation)
- [x] add a section in the ILS documentation to explain all this and how to use it

### Extra details

**Patron data**

In ILS, records normally store only the patron PID, and then it is the `$ref` that resolves the patron info. Patron info are stored in:
- Loans
- Acquisitions
- ILLs
- Document requests

It should be enough to anonymise info in the DB (see below) and re-index all records referencing this patron PID.

**User info in the DB**

Code to be tested:

```
    with db.session.begin_nested():
        user_identity = UserIdentity.query.filter(UserIdentity.id_user == user_id).one()
        // check table structure if to be anonymized. Data only in case of OAuth (GitHub, CERN, etc..)

        remote_account = RemoteAccount.query.filter(RemoteAccount.user_id == user_id).one()
        // check table structure if to be anonymized. Data only in case of OAuth (GitHub, CERN, etc..)

        user_profile = UserProfile.query.filter(UserProfile.user_id == user_id).one()
        // check table structure if to be anonymized

        user = User.query.filter(User.id == user_id).one()
        // check table structure if to be anonymized
```
